# Define the goal
geometry_msgs/Pose[] frames
float32[] time
bool incremental
---
# Define the result
geometry_msgs/Pose final_frame
float32 position_error_norm
float32 orientation_error_angle
---
# Define a feedback message
geometry_msgs/PoseStamped current_reference
geometry_msgs/PoseStamped current_pose
int32 current_segment_id
