solver_options:
    regularization: 1e-6
    back_end: "qpoases"

stack:
    - ["Wheel_FL", "Wheel_FR", "Wheel_HR", "Wheel_HL"]
    - ["Waist"]
    - ["Postural"]
constraints: ["JointLimits", "VelocityLimits", "ConvexHull"]

ConvexHull:
    lib_name: "libCartesioConvexHullAddon.so"
    type: "ConvexHull"
    contact_links: ["wheel_1", "wheel_2", "wheel_3"]
    safety_margin: 0.01

Wheel_FL:
    type: "Cartesian"
    distal_link: "wheel_1"

Wheel_FR:
    type: "Cartesian"
    distal_link: "wheel_2"

Wheel_HL:
    type: "Cartesian"
    distal_link: "wheel_3"

Wheel_HR:
    type: "Cartesian"
    distal_link: "wheel_4"

LeftArm:
    type: "Cartesian"
    distal_link: "arm1_8"
    base_link: "pelvis"
    lambda: 0.1

RightArm:
    type: "Cartesian"
    distal_link: "arm2_8"
    base_link: "pelvis"
    lambda: 0.1
    
Waist:
    type: "Cartesian"
    distal_link: "pelvis"
    lambda: 0.1
    
Postural:
    type: "Postural"
    lambda: 0.01
    weight:
        VIRTUALJOINT_1: 0.0
        VIRTUALJOINT_2: 0.0
        VIRTUALJOINT_3: 0.0
        VIRTUALJOINT_4: 0.0
        VIRTUALJOINT_5: 0.0
        VIRTUALJOINT_6: 0.0

    
Com:
    type: "Com"
    lambda: 0.05
    indices: [0, 1]
    weight: 10
