solver_options:
    regularization: 1e-6
    back_end: "qpoases"

stack:
    - ["Waist", "Car", "Wheel_FL", "Wheel_FR", "Wheel_HR", "Wheel_HL", "Steering_FL", "Steering_FR", "Steering_HL", "Steering_HR", "LeftArm", "RightArm"]
    - ["Ankle_FL", "Ankle_FR", "Ankle_HR", "Ankle_HL", "Rolling_FL", "Rolling_FR", "Rolling_HL", "Rolling_HR"]
    - ["Postural"]
    
constraints: ["JointLimits", "VelocityLimits"]

Car:
    type: "Cartesian"
    distal_link: "car_frame"
    lambda: 0.1

Steering_FL:
    type: "CentauroSteering"
    wheel_name: "wheel_1"
    lib_name: "libCentauroCartesioAddon.so"
    lambda: 0.1
    
Steering_FR:
    type: "CentauroSteering"
    wheel_name: "wheel_2"
    lib_name: "libCentauroCartesioAddon.so"
    lambda: 0.1
    
Steering_HL:
    type: "CentauroSteering"
    wheel_name: "wheel_3"
    lib_name: "libCentauroCartesioAddon.so"
    lambda: 0.1
    
Steering_HR:
    type: "CentauroSteering"
    wheel_name: "wheel_4"
    lib_name: "libCentauroCartesioAddon.so"
    lambda: 0.1
    
Rolling_FL:
    type: "WheelRolling"
    wheel_name: "wheel_1"
    lib_name: "libCentauroCartesioAddon.so"
    wheel_radius: 0.078
    
Rolling_FR:
    type: "WheelRolling"
    wheel_name: "wheel_2"
    lib_name: "libCentauroCartesioAddon.so"
    wheel_radius: 0.078
    
Rolling_HL:
    type: "WheelRolling"
    wheel_name: "wheel_3"
    lib_name: "libCentauroCartesioAddon.so"
    wheel_radius: 0.078
    
Rolling_HR:
    type: "WheelRolling"
    wheel_name: "wheel_4"
    lib_name: "libCentauroCartesioAddon.so"
    wheel_radius: 0.078
    
Waist:
    type: "Cartesian"
    distal_link: "pelvis"
    base_link: "car_frame"
    lambda: 0.1
    
Wheel_FL:
    type: "Cartesian"
    distal_link: "wheel_1"
    base_link: "car_frame"
    indices: [0, 1, 2]
    lambda: 0.1
    disabled_joints: ["ankle_yaw_1", "j_wheel_1"]

Wheel_FR:
    type: "Cartesian"
    distal_link: "wheel_2"
    base_link: "car_frame"
    indices: [0, 1, 2]
    lambda: 0.1
    disabled_joints: ["ankle_yaw_2", "j_wheel_2"]

Wheel_HL:
    type: "Cartesian"
    distal_link: "wheel_3"
    base_link: "car_frame"
    indices: [0, 1, 2]
    lambda: 0.1
    disabled_joints: ["ankle_yaw_3", "j_wheel_3"]

Wheel_HR:
    type: "Cartesian"
    distal_link: "wheel_4"
    base_link: "car_frame"
    indices: [0, 1, 2]
    lambda: 0.1
    disabled_joints: ["ankle_yaw_4", "j_wheel_4"]

Ankle_FL:
    type: "Cartesian"
    distal_link: "ankle1_1"
    base_link: "car_frame"
    indices: [3, 4]
    lambda: 0.02
    weight: 10.0

Ankle_FR:
    type: "Cartesian"
    distal_link: "ankle1_2"
    base_link: "car_frame"
    indices: [3, 4]
    lambda: 0.02
    weight: 10.0

Ankle_HL:
    type: "Cartesian"
    distal_link: "ankle1_3"
    base_link: "car_frame"
    indices: [3, 4]
    lambda: 0.02
    weight: 10.0

Ankle_HR:
    type: "Cartesian"
    distal_link: "ankle1_4"
    base_link: "car_frame"
    indices: [3, 4]
    lambda: 0.02
    weight: 10.0
    
LeftArm:
    type: "Cartesian"
    distal_link: "arm1_8"
    base_link: "pelvis"
    lambda: 0.1

RightArm:
    type: "Cartesian"
    distal_link: "arm2_8"
    base_link: "pelvis"
    lambda: 0.1
    
Postural:
    type: "Postural"
    lambda: 0.01

    
Com:
    type: "Com"
    lambda: 0.05
    indices: [0, 1]
    weight: 10
