
stack:
    - ["LeftFoot", "RightFoot", "Com"]
    - ["LeftHand", "RightHand", "TorsoRotZ"]
    - ["Postural"]
    
constraints: ["JointLimits", "VelocityLimits"]

LeftFoot:
    type: "Cartesian"
    distal_link: "l_sole"

RightFoot:
    type: "Cartesian"
    distal_link: "r_sole"

TorsoRotZ:
    type: "Cartesian"
    distal_link: "DWYTorso"
    indices: [5]
    lambda: 0.05

Com:
    type: "Com"
    indices: [0, 1]
    
Postural:
    type: "Postural"
    lambda: 0.01
    weight:
    WaistLat: 100.0
    LKneePitch: 10.0
    RKneePitch: 10.0

LeftHand:
    type: "Cartesian"
    distal_link: "LWrMot3"
    lambda: 0.1

RightHand:
    type: "Cartesian"
    distal_link: "RWrMot3"
    lambda: 0.1