solver_options:
    regularization: 1e-3
    back_end: "osqp"

stack:
    - ["AngularMomentum", "Com"]
    #- ["Com"]
    #- ["LeftFoot", "RightFoot"]
    #- ["LeftArm", "RightArm"]
    #- ["LeftArm"]
    - ["Torso"]
    #- ["FloatingBase"]
    #- ["Torso", "LeftFootLocal", "RightFootLocal", "RightArmLocal", "LeftArmLocal"]
    #- ["FloatingBase", "LeftFootLocal", "RightFootLocal", "RightArmLocal", "LeftArmLocal"]
    - ["Postural"]

constraints: ["JointLimits", "VelocityLimits"]

FloatingBase:
    type: "Cartesian"
    name: "floating_base"
    distal_link: "base_link"
    lambda: 0.1

Torso:
    type: "Cartesian"
    name: "torso"
    distal_link: "torso"

AngularMomentum:
    type: "AngularMomentum"

LeftFootLocal:
    type: "Cartesian"
    name: "left_foot"
    distal_link: "l_sole"
    base_link: "base_link"

RightFootLocal:
    type: "Cartesian"
    name: "right_foot"
    distal_link: "r_sole"
    base_link: "base_link"

LeftFoot:
    type: "Cartesian"
    name: "left_foot"
    distal_link: "l_sole"

RightFoot:
    type: "Cartesian"
    name: "right_foot"
    distal_link: "r_sole"

LeftArmLocal:
    type: "Cartesian"
    name: "left_hand"
    distal_link: "LSoftHand"
    base_link: "torso"

RightArmLocal:
    type: "Cartesian"
    name: "right_hand"
    distal_link: "RSoftHand"
    base_link: "torso"

LeftArm:
    type: "Cartesian"
    name: "left_hand"
    distal_link: "LSoftHand"
    lambda: 0.1

RightArm:
    type: "Cartesian"
    name: "right_hand"
    distal_link: "RSoftHand"
    base_link: "base_link"
    lambda: 0.1
    
Postural:
    type: "Postural"
    lambda: 1.0
    weight:
        VIRTUALJOINT_1: 0.0
        VIRTUALJOINT_2: 0.0
        VIRTUALJOINT_3: 0.0
        VIRTUALJOINT_4: 0.0
        VIRTUALJOINT_5: 0.0
        VIRTUALJOINT_6: 0.0

Com:
    type: "Com"
    lambda: 0.
    #indices: [0, 1]
    #weight: 10

JointLimits:
    type: "JointLimits"


VelocityLimits:
    type: "VelocityLimits"
