solver_options:
    regularization: 1e-6
    back_end: "osqp"

stack:
    - ["EndEffector"]
    - ["Elbow"]
    - ["Postural"]
constraints: ["JointLimits", "VelocityLimits"]

EndEffector:
    type: "Cartesian"
    distal_link: "kuka_lwr_7_link"

Elbow:
    type: "Cartesian"
    distal_link: "kuka_lwr_4_link"
    
Postural:
    type: "Postural"
    lambda: 0.01
